import type { Product } from "@/lib/types";

export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    slug: "khatch-lager",
    name: "Khatch Lager",
    category: "Bière",
    description: "Lager blonde légère, sèche et très clean.",
    image_path: "/products/khatch-lager.png",
    price: 45,
    volume_ml: 330,
    alcohol_pct: 5,
    visual_tone: "amber",
    bottle_style: "beer",
    active: true,
    stock_count: null,
    sort_order: 1
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    slug: "khatch-valley-whisky",
    name: "Khatch Valley Whisky",
    category: "Whisky",
    description: "American whiskey avec maturation en fûts de chêne arménien.",
    image_path: "/products/khatch-valley-whisky.png",
    price: 180,
    volume_ml: 700,
    alcohol_pct: 42,
    visual_tone: "oak",
    bottle_style: "square",
    active: true,
    stock_count: null,
    sort_order: 2
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    slug: "khatch-vodka",
    name: "Khatch Vodka",
    category: "Vodka",
    description: "Vodka ultra-pure à base de blé, finition très douce.",
    image_path: "/products/khatch-vodka.png",
    price: 120,
    volume_ml: 700,
    alcohol_pct: 40,
    visual_tone: "clear",
    bottle_style: "square",
    active: true,
    stock_count: null,
    sort_order: 3
  },
  {
    id: "44444444-4444-4444-8444-444444444444",
    slug: "khatch-botanical-gin",
    name: "Khatch Botanical Gin",
    category: "Gin",
    description: "Gin aux botaniques arméniennes : genièvre, abricot sec et herbes sauvages.",
    image_path: "/products/khatch-botanical-gin.png",
    price: 150,
    volume_ml: 700,
    alcohol_pct: 41,
    visual_tone: "mist",
    bottle_style: "round",
    active: true,
    stock_count: null,
    sort_order: 4
  },
  {
    id: "55555555-5555-4555-8555-555555555555",
    slug: "valley-rum",
    name: "Valley Rum",
    category: "Rhum",
    description: "Rhum ambré, pensé autour de notes vanillées et fruitées.",
    image_path: "/products/valley-rum.png",
    price: 165,
    volume_ml: 700,
    alcohol_pct: 40,
    visual_tone: "rum",
    bottle_style: "round",
    active: true,
    stock_count: null,
    sort_order: 5
  },
  {
    id: "66666666-6666-4666-8666-666666666666",
    slug: "khatch-blanco",
    name: "Khatch Blanco",
    category: "Tequila",
    description: "Tequila blanco premium, identité très minimaliste.",
    image_path: "/products/khatch-blanco.png",
    price: 190,
    volume_ml: 700,
    alcohol_pct: 40,
    visual_tone: "silver",
    bottle_style: "round",
    active: true,
    stock_count: null,
    sort_order: 6
  },
  {
    id: "77777777-7777-4777-8777-777777777777",
    slug: "khatch-armenian-brandy",
    name: "Khatch Armenian Brandy",
    category: "Brandy",
    description: "Brandy de raisin, inspiré de la tradition arménienne.",
    image_path: "/products/khatch-armenian-brandy.png",
    price: 240,
    volume_ml: 700,
    alcohol_pct: 43,
    visual_tone: "brandy",
    bottle_style: "round",
    active: true,
    stock_count: null,
    sort_order: 7
  },
  {
    id: "88888888-8888-4888-8888-888888888888",
    slug: "tsiran",
    name: "Tsiran",
    category: "Liqueur",
    description: "Liqueur d’abricot arménien, ronde et délicatement fruitée.",
    image_path: "/products/tsiran.png",
    price: 135,
    volume_ml: 500,
    alcohol_pct: 28,
    visual_tone: "apricot",
    bottle_style: "round",
    active: true,
    stock_count: null,
    sort_order: 8
  }
];
